<a href="https://colab.research.google.com/github/xiaoruiyu405/dse-ml-2026/blob/main/processing_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install bertopic
from bertopic.backend import BaseEmbedder
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer


class TfIdfEmbedder(BaseEmbedder):
    def __init__(self, vocabulary: list[str] | None = None, *args, **kwargs):
        super().__init__()
        self.embedding_model: TfidfVectorizer = TfidfVectorizer(*args, **kwargs)
        self.vocabulary = vocabulary
        if vocabulary is not None:
            self.embedding_model.fit(self.vocabulary)

    def embed(self, documents, verbose=True):
        if self.vocabulary is None:
            print("Call 'fit_transform'...")
            return self.embedding_model.fit_transform(documents)
        print("Call 'transform' only...")
        return self.embedding_model.transform(documents)


class CountVectorizerEmbedder(BaseEmbedder):
    def __init__(self, vocabulary: list[str] | None = None, *args, **kwargs):
        super().__init__()
        self.embedding_model: CountVectorizer = CountVectorizer(*args, **kwargs)
        self.vocabulary = vocabulary
        if vocabulary is not None:
            self.embedding_model.fit(self.vocabulary)

    def embed(self, documents, verbose=True):
        if self.vocabulary is None:
            print("Call 'fit_transform'...")
            return self.embedding_model.fit_transform(documents)
        print("Call 'transform' only...")
        return self.embedding_model.transform(documents)


class SentenceTransformerSmall(BaseEmbedder):
    def __init__(self):
        super().__init__()
        self.embedding_model = SentenceTransformer("all-minilm-l6-v2")

    def embed(self, documents, verbose=True):
        embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
        return embeddings


class SentenceTransformerLarge(BaseEmbedder):
    def __init__(self):
        super().__init__()
        self.embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

    def embed(self, documents, verbose=True):
        embeddings = self.embedding_model.encode(documents, show_progress_bar=verbose)
        return embeddings

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.13/dist-packages (from bertopic) (0.8.44)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (2.1.3)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.13/dist-packages (from bertopic) (2.2.3)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.13/dist-packages (from bertopic) (5.7.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.13/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.13/dist-packages (from bertopic) (0.44.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.13/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.13/dist-packages (from hdbscan>=0.8.29->bertopic) (1.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.1.5->bertopic) (2026.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from plotly>=4.7.0->bertopic) (26.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.16.1)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.23.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.29.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.13/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.16.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.13/dist-packages (from umap-learn>=0.5.0->bertopic) (0.61.2)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.13/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.32.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.0->hdbscan>=0.8.29->bertopic) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 9.9 MB/s eta 0:00:00
Installing collected packages: bertopic
Successfully installed bertopic-0.17.4

In [7]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from tqdm import tqdm

tqdm.pandas()

### 1. Prepare parlamint dataset

#### 1.1. Load Dataset (Sentence-Wise)

In [12]:
# Load parlamint dataset
df_parlamint = pd.read_csv("/content/drive/MyDrive/dse-ml-2026/materials/datasets/parlamint/parlamint-it-is-2022.txt", sep="\t").head(10000)
df_parlamint_subset = df_parlamint.copy(deep=True).head(100)
df_parlamint

,ID,Parent_ID,Text
0,ParlaMint-IS_2022-01-17-20.seg2.1,ParlaMint-IS_2022-01-17-20.u1,President of the United States reports:
1,ParlaMint-IS_2022-01-17-20.seg3.1,ParlaMint-IS_2022-01-17-20.u1,"I have decided, according to the proposal of t..."
2,ParlaMint-IS_2022-01-17-20.seg4.1,ParlaMint-IS_2022-01-17-20.u1,"Arrange sites, January 11th, 2022."
3,ParlaMint-IS_2022-01-17-20.seg6.1,ParlaMint-IS_2022-01-17-20.u1,Katrín Jakobsdóttir's daughter.
4,ParlaMint-IS_2022-01-17-20.seg7.1,ParlaMint-IS_2022-01-17-20.u1,Presidential Letters for a meeting of the Gene...
...,...,...,...
9995,ParlaMint-IS_2022-01-27-28.seg113.4,ParlaMint-IS_2022-01-27-28.u58,"Some of these are good, but the big picture is..."
9996,ParlaMint-IS_2022-01-27-28.seg113.5,ParlaMint-IS_2022-01-27-28.u58,The variable was never taken out whether it wa...
9997,ParlaMint-IS_2022-01-27-28.seg114.1,ParlaMint-IS_2022-01-27-28.u58,I will not vote with this case.
9998,ParlaMint-IS_2022-01-27-28.seg114.2,ParlaMint-IS_2022-01-27-28.u58,I won't get in the way of this case.
9999,ParlaMint-IS_2022-01-27-28.seg114.3,ParlaMint-IS_2022-01-27-28.u58,I will be embarrassed by the release of this c...

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#### 1.2. Group Dataset per Utterance

In [13]:
# Group sentence by utterance (=Parent_ID)
df_parlamint_grouped = (df_parlamint.groupby(["Parent_ID"])["Text"]
                        .apply(lambda s: " ".join(s))
                        .reset_index(name="utterance_text"))
print(f"Unique utterances: {df_parlamint_grouped.shape[0]}")
df_parlamint_grouped

Unique utterances: 660

,Parent_ID,utterance_text
0,ParlaMint-IS_2022-01-17-20.u1,President of the United States reports: I have...
1,ParlaMint-IS_2022-01-17-20.u10,"Before the weekend, an article by Stefánssonar..."
2,ParlaMint-IS_2022-01-17-20.u11,"I read this decision in Perconte, which is not..."
3,ParlaMint-IS_2022-01-17-20.u12,"In fact, this is shown in the letter quoted by..."
4,ParlaMint-IS_2022-01-17-20.u13,"Yes, that's right. That's right. A senator who..."
...,...,...
655,ParlaMint-IS_2022-01-27-28.u58,Here we vote for a case that involves massive ...
656,ParlaMint-IS_2022-01-27-28.u6,"I come up here to agree with this, this case i..."
657,ParlaMint-IS_2022-01-27-28.u7,In his article at Science yesterday and also i...
658,ParlaMint-IS_2022-01-27-28.u8,The president still reminds us of a limited ta...
659,ParlaMint-IS_2022-01-27-28.u9,I wanted to add what I came in here earlier th...

In [14]:
sample_utterance = df_parlamint[df_parlamint["Parent_ID"] == "ParlaMint-IS_2022-01-17-20.u1"]["Text"]
sample_utterance

0              President of the United States reports:
1    I have decided, according to the proposal of t...
2                   Arrange sites, January 11th, 2022.
3                      Katrín Jakobsdóttir's daughter.
4    Presidential Letters for a meeting of the Gene...
5    I'd like to use this opportunity here after re...
Name: Text, dtype: object

### 2. Different Text Embedding Algorithms

#### 2.1. Count Vectorizer (Sparse) Embeddings

In [15]:
# Adding the whole parlamint dataset as vocabulary
# cv_model = CountVectorizerEmbedder(vocabulary=df_parlamint["Text"].to_list(), min_df=100, stop_words='english',
#                                    n_gram_range=(1, 3))

# Adding just the utterance sample as vocabulary
cv_model = CountVectorizerEmbedder(vocabulary=df_parlamint_grouped["utterance_text"], max_features=10,stop_words='english')

In [ ]:
cv_embeddings = cv_model.embed(sample_utterance)
print(f"Number features: {len(cv_model.embedding_model.get_feature_names_out())}", cv_model.embedding_model.get_feature_names_out())
print(f"Shape embedding array: {cv_embeddings.toarray().shape}")
df_cv_output = pd.DataFrame(columns=cv_model.embedding_model.get_feature_names_out(), data=cv_embeddings.toarray())
df_cv_output

Call 'transform' only...
Number features: 10 ['council' 'government' 'health' 'just' 'like' 'minister' 'need' 'people'
 'think' 'time']
Shape embedding array: (6, 10)

,council,government,health,just,like,minister,need,people,think,time
0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0

#### 2.2 TF-IDF (Sparse) Embeddings

In [16]:
# Adding the whole parlamint dataset as vocabulary
# tfidf_model = TfIdfEmbedder(vocabulary=df_parlamint["Text"].to_list(), min_df=100, stop_words='english')

# Adding just the utterance sample as vocabulary
tfidf_model = TfIdfEmbedder(vocabulary=df_parlamint_grouped["utterance_text"], max_features=10, stop_words='english')

In [ ]:
tfidf_embeddings = tfidf_model.embed(sample_utterance)
print(f"Number features: {len(tfidf_model.embedding_model.get_feature_names_out())}", tfidf_model.embedding_model.get_feature_names_out())
print(f"Shape embedding array: {tfidf_embeddings.toarray().shape}")
df_tfidf_output = pd.DataFrame(columns=tfidf_model.embedding_model.get_feature_names_out(), data=tfidf_embeddings.toarray())
df_tfidf_output

Call 'transform' only...
Number features: 10 ['council' 'government' 'health' 'just' 'like' 'minister' 'need' 'people'
 'think' 'time']
Shape embedding array: (6, 10)

,council,government,health,just,like,minister,need,people,think,time
0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,0.735172,0.0,0.0,0.0,0.0,0.677881,0.0,0.0,0.0,0.0
2,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
5,0.000000,0.0,0.0,0.0,1.0,0.000000,0.0,0.0,0.0,0.0

#### 2.3 Sentence Transformer (Dense) Embeddings

In [17]:
st_model_small = SentenceTransformer('all-minilm-l6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [18]:
# Encode sentence-wise
# sample_utterance is a pandas Series; encode expects a string or a list of strings.
st_embeddings = st_model_small.encode(sample_utterance.tolist())
print(f"Number of sentence embeddings: {len(st_embeddings)}")
print(f"Shape embedding array: {st_embeddings.shape}")
st_embeddings

Number of sentence embeddings: 6
Shape embedding array: (6, 384)

array([[ 0.00364315,  0.0075753 , -0.01352419, ..., -0.01752402,
         0.00990044,  0.06021778],
       [-0.04760474, -0.06898868,  0.02710493, ..., -0.06230193,
        -0.14385448,  0.03971656],
       [-0.01698016, -0.04804511, -0.01744974, ..., -0.03905804,
        -0.07595797,  0.00352384],
       [-0.08331395, -0.04858721,  0.00143909, ...,  0.03839727,
         0.06088394, -0.01607143],
       [-0.07626822, -0.06527785,  0.06610004, ...,  0.02295852,
        -0.10826011, -0.06591922],
       [ 0.01009847, -0.0453703 ,  0.04564784, ..., -0.00065686,
        -0.0854706 , -0.00425592]], dtype=float32)

In [19]:
# Encode utterance-wise
st_embeddings_u = st_model_small.encode(" ".join(sample_utterance))
print(f"Number features: {len(st_embeddings_u)}")
print(f"Shape embedding array: {st_embeddings_u.shape}")
st_embeddings_u

Number features: 384
Shape embedding array: (384,)

array([-5.19020185e-02, -1.02959432e-01,  6.31395429e-02,  2.98001897e-02,
       -2.51417439e-02, -9.66061372e-03, -7.38494396e-02, -2.23561283e-02,
       -6.58514723e-02,  7.95470644e-03, -6.14717044e-02,  9.11198277e-03,
       -7.41380826e-02, -8.91720783e-03,  4.29924875e-02,  3.98151763e-02,
        5.71963436e-04, -2.14750301e-02,  4.03534435e-02, -3.10852192e-03,
        4.81391363e-02,  3.13877873e-02,  2.43081450e-02,  3.66791897e-03,
       -4.10232022e-02, -1.00539709e-02, -1.73179135e-02, -3.86848114e-02,
       -1.10482778e-02,  6.46823421e-02,  5.51152155e-02, -5.29571762e-03,
        7.86908716e-02,  2.21064594e-02,  5.85365146e-02,  2.10544281e-03,
        5.57183810e-02,  3.54421027e-02,  3.88754159e-02, -5.69796637e-02,
       -1.24397287e-02, -6.79902136e-02,  2.59145629e-02, -4.62712254e-03,
       -3.93818915e-02,  4.40331772e-02, -3.18673030e-02, -2.18536193e-03,
       -3.43883298e-02,  6.45774975e-02,  4.68759844e-03,  1.60151464e-03,
        1.24297533e-02, -1.39933914e-01,  4.85735498e-02,  8.35392103e-02,
       -5.54768592e-02, -7.94954896e-02,  3.52739431e-02, -1.56451538e-02,
       -7.82986730e-02, -5.40732779e-02, -9.10800546e-02,  2.96729449e-02,
        2.66688224e-02,  1.55667756e-02,  5.79194613e-02,  3.17628942e-02,
        4.89223041e-02, -4.00570454e-03,  2.41414253e-02,  4.46502902e-02,
       -2.40369756e-02, -5.95684648e-02, -1.38046024e-02,  1.14792641e-02,
        3.08526848e-02,  7.52162039e-02,  5.72752059e-02,  8.01658072e-03,
       -4.04782705e-02,  3.12746540e-02,  9.66266990e-02, -2.74539441e-02,
        3.29840705e-02,  1.94528457e-02, -3.80517803e-02, -2.27975752e-02,
       -6.42892942e-02,  2.35426538e-02, -2.39265393e-02, -6.75097853e-02,
        4.01866809e-03,  5.95572852e-02, -1.29172593e-01,  2.20304704e-03,
        2.00322177e-02, -2.35908292e-02,  5.03619835e-02,  4.83760498e-02,
       -3.89941894e-02,  1.06105275e-01, -4.23192158e-02, -4.33825180e-02,
       -1.01408876e-01,  3.85576254e-03, -2.96520609e-02, -6.14200905e-02,
       -1.74139440e-02,  5.27417399e-02,  1.50506466e-03, -1.39855919e-02,
        1.89992618e-02, -8.32699835e-02, -2.35255924e-03,  8.75058025e-03,
        3.01993955e-02,  1.12108383e-02,  3.66522558e-02, -8.79314542e-03,
       -6.21791231e-03,  4.52932715e-02, -2.77698413e-02, -1.58737693e-02,
       -2.97475886e-02, -4.20140103e-02,  1.70941441e-03, -1.64824126e-33,
       -4.02345359e-02, -2.29078867e-02,  5.65283708e-02,  6.85211495e-02,
        2.99266595e-02,  8.63669887e-02,  4.83634463e-03, -6.94823861e-02,
        4.24841158e-02, -7.24619552e-02, -3.03379353e-02, -1.05767697e-02,
        1.08414255e-01, -5.62360100e-02, -9.98089761e-02, -6.33733571e-02,
        4.95769568e-02,  4.39037904e-02, -1.35309612e-02, -3.62109616e-02,
        2.55938508e-02, -4.66833636e-02,  6.69551566e-02,  5.37807010e-02,
        1.13697886e-01,  2.11778637e-02, -1.81589220e-02,  1.06483130e-02,
        5.41634969e-02,  2.72313263e-02, -4.00837772e-02,  3.15782875e-02,
       -2.25818884e-02,  6.92701116e-02,  1.28514087e-03,  2.24844050e-02,
       -8.40351917e-03, -3.23565415e-04, -4.57269512e-03,  7.34137651e-03,
        5.29095251e-03,  3.74797639e-03, -1.20444009e-02, -2.08908208e-02,
        9.88593623e-02, -4.46117595e-02,  2.33832337e-02,  1.06673032e-01,
        9.03974921e-02, -3.79968546e-02, -5.00639379e-02,  1.40769295e-02,
       -9.09865499e-02, -2.96056308e-02,  3.62678431e-03,  1.15826763e-02,
       -5.56659559e-03, -8.21885318e-02,  3.49215567e-02, -6.36989600e-04,
        7.54302964e-02,  5.15043400e-02, -5.08631617e-02,  2.38396749e-02,
       -4.28086072e-02, -2.71378383e-02, -6.70645386e-02, -3.14144045e-02,
        5.31932479e-03, -5.94315715e-02,  9.40876976e-02,  1.83409415e-02,
       -4.44104197e-04,  3.41898240e-02, -7.34981820e-02,  6.19949177e-02,
        1.40009657e-01,  2.69954535e-03,  2.07903832e-02,  3.59098651e-02,
       -1.50815751e-02,  5.02267890e-02,  7.14422911e-02,  1.16507048e-02,
        9.08135995e-02,  1.62468217e-02,  4.60546836e-03, -1.79179534e-02,
       -1.63843874e-02,  4.25201543e-02, -8.37820023e-02, -6.67073801e-02,
        1.12634972e-01,  5.88681474e-02, -1.18632959e-02, -1.49489802e-33,
        1.13438375e-01,  1.15160923e-02,  1.60573479e-02, -3.90678570e-02,
       -6.10374613e-03, -9.86833405e-03, -3.54821980e-02,  1.40406676e-02,
        1.53267300e-02, -3.20872106e-02, -4.11133235e-03,  4.29360643e-02,
        5.47034331e-02,  2.11893320e-02, -3.00956909e-02, -4.43021813e-03,
        1.13701709e-01, -8.44393820e-02, -3.18638422e-02, -2.20031049e-02,
        1.15142828e-02,  3.74506004e-02, -2.77590379e-02, -7.83092156e-02,
        1.18805841e-02, -9.20188650e-02,  1.24171607e-01, -5.45978211e-02,
       -3.03370561e-02,  1.42644756e-02, -1.17194004e-01, -6.71947673e-02,
       -7.83260167e-02,  6.02756515e-02,  6.16755262e-02,  6.07781522e-02,
        2.08572522e-02, -8.85275155e-02,  3.47588547e-02,  5.24160974e-02,
        4.12596539e-02,  4.11491953e-02, -1.04474211e-02,  3.06681488e-02,
        8.20398796e-03,  2.54724850e-03, -4.45929542e-02,  1.69353560e-02,
       -7.14864358e-02, -3.93489189e-02, -8.94944072e-02, -2.46422775e-02,
       -5.06531037e-02, -5.58770709e-02,  2.50644051e-02,  6.93076923e-02,
       -5.80172576e-02, -3.65523323e-02,  6.17346689e-02, -2.99313269e-03,
       -6.63670152e-03, -2.17994191e-02, -3.34859006e-02, -3.31427120e-02,
        1.29592940e-02, -5.75143769e-02, -1.67515296e-02,  9.66030546e-03,
        7.29947165e-02,  5.37132211e-02,  2.83475183e-02, -1.11339852e-01,
       -6.06608950e-02,  3.27444375e-02,  2.85430513e-02, -1.16369659e-02,
        1.09426472e-02, -6.50288817e-03, -1.40469167e-02, -1.66090205e-02,
       -4.77099940e-02,  7.87681490e-02, -8.81384686e-02, -5.25563657e-02,
        4.09737155e-02, -3.34049179e-03,  3.12436111e-02, -1.33758290e-02,
        4.30774316e-02, -1.26053870e-03,  1.89442951e-02, -3.80163230e-02,
        6.11947849e-02,  1.98238939e-02,  2.22714189e-02, -5.02717228e-08,
        6.80646747e-02,  5.38175069e-02, -8.39098766e-02,  3.51661030e-04,
        5.71653284e-02, -3.78379077e-02, -6.28212169e-02, -1.47414267e-01,
       -3.45255099e-02,  4.37515639e-02,  1.26887724e-01,  3.73939052e-02,
       -7.84284342e-03, -4.35751416e-02,  6.76912442e-02, -4.59159026e-03,
       -6.78891391e-02, -8.65934603e-03, -5.77962697e-02, -3.04820240e-02,
       -5.82125112e-02,  2.05211341e-02, -2.03502201e-03,  1.89462509e-02,
        2.03901399e-02, -1.27997044e-02,  2.37776041e-02,  4.27544825e-02,
       -1.05391003e-01, -2.60263234e-02, -5.73621653e-02,  5.93618453e-02,
       -1.22949220e-01, -4.30588499e-02,  2.51190979e-02, -6.99013397e-02,
       -1.12665169e-01,  1.37773845e-02,  8.06678981e-02,  1.31958500e-02,
        8.60544294e-03,  4.21196148e-02,  1.37123885e-02,  6.58888519e-02,
       -1.52289402e-02,  8.02278705e-03, -6.44207746e-03,  8.77849106e-03,
        3.25865141e-04,  7.66182877e-03, -1.11664049e-01,  5.33220321e-02,
        9.84750241e-02, -5.69626614e-02,  4.52251583e-02,  1.12189271e-01,
        1.15438700e-02, -1.77373663e-02, -3.22160646e-02,  1.37432784e-04,
       -2.66184490e-02, -7.50834541e-03, -1.31233528e-01, -6.80764066e-03],
      dtype=float32)

### 3. Encode whole Parlamint Dataset

#### 3.1 Encode with Sentence Transformer

In [20]:
# Encode utterance-wise dataset
df_parlamint_embeddings_per_utterance = st_model_small.encode(df_parlamint_grouped["utterance_text"].to_list(),
                                                     show_progress_bar=True)

# Encode sentence-wise dataset
df_parlamint_embeddings_per_sentence = st_model_small.encode(df_parlamint["Text"].to_list(), show_progress_bar=True)

Batches:   0%|          | 0/21 [00:00<?, ?it/s]

Batches:   0%|          | 0/313 [00:00<?, ?it/s]

In [21]:
df_parlamint_grouped["embedding"] = list(df_parlamint_embeddings_per_utterance)
df_parlamint_grouped

,Parent_ID,utterance_text,embedding
0,ParlaMint-IS_2022-01-17-20.u1,President of the United States reports: I have...,"[-0.05190201, -0.102959484, 0.063139565, 0.029..."
1,ParlaMint-IS_2022-01-17-20.u10,"Before the weekend, an article by Stefánssonar...","[-0.104611516, 0.06670193, -0.056569587, -0.02..."
2,ParlaMint-IS_2022-01-17-20.u11,"I read this decision in Perconte, which is not...","[-0.0037422264, 0.07299824, -0.017051956, -0.0..."
3,ParlaMint-IS_2022-01-17-20.u12,"In fact, this is shown in the letter quoted by...","[-0.1063038, 0.06314155, -0.014823508, 0.01412..."
4,ParlaMint-IS_2022-01-17-20.u13,"Yes, that's right. That's right. A senator who...","[-0.03764075, 0.10380772, -0.061545722, 0.0093..."
...,...,...,...
655,ParlaMint-IS_2022-01-27-28.u58,Here we vote for a case that involves massive ...,"[-0.016700177, -0.07529929, 0.029732978, 0.003..."
656,ParlaMint-IS_2022-01-27-28.u6,"I come up here to agree with this, this case i...","[-0.0046804934, 0.05790165, -0.003511662, -0.0..."
657,ParlaMint-IS_2022-01-27-28.u7,In his article at Science yesterday and also i...,"[-0.026387008, 0.05542075, 0.045418274, 0.0204..."
658,ParlaMint-IS_2022-01-27-28.u8,The president still reminds us of a limited ta...,"[0.017418494, -0.035377957, 0.09752447, -0.021..."
659,ParlaMint-IS_2022-01-27-28.u9,I wanted to add what I came in here earlier th...,"[-0.07245073, 0.04307242, 0.021605698, -0.0120..."

In [22]:
df_parlamint["embedding"] = list(df_parlamint_embeddings_per_sentence)
df_parlamint

,ID,Parent_ID,Text,embedding
0,ParlaMint-IS_2022-01-17-20.seg2.1,ParlaMint-IS_2022-01-17-20.u1,President of the United States reports:,"[0.0036431411, 0.0075753005, -0.013524175, 0.0..."
1,ParlaMint-IS_2022-01-17-20.seg3.1,ParlaMint-IS_2022-01-17-20.u1,"I have decided, according to the proposal of t...","[-0.047604747, -0.06898866, 0.027104955, 0.042..."
2,ParlaMint-IS_2022-01-17-20.seg4.1,ParlaMint-IS_2022-01-17-20.u1,"Arrange sites, January 11th, 2022.","[-0.016980128, -0.04804515, -0.017449748, 0.01..."
3,ParlaMint-IS_2022-01-17-20.seg6.1,ParlaMint-IS_2022-01-17-20.u1,Katrín Jakobsdóttir's daughter.,"[-0.08331394, -0.04858722, 0.0014390874, -0.04..."
4,ParlaMint-IS_2022-01-17-20.seg7.1,ParlaMint-IS_2022-01-17-20.u1,Presidential Letters for a meeting of the Gene...,"[-0.07626822, -0.06527785, 0.06610004, 0.01071..."
...,...,...,...,...
9995,ParlaMint-IS_2022-01-27-28.seg113.4,ParlaMint-IS_2022-01-27-28.u58,"Some of these are good, but the big picture is...","[-0.010372346, -0.04594692, -0.015732536, -0.0..."
9996,ParlaMint-IS_2022-01-27-28.seg113.5,ParlaMint-IS_2022-01-27-28.u58,The variable was never taken out whether it wa...,"[0.0029584889, 0.07198218, -0.037595496, 0.068..."
9997,ParlaMint-IS_2022-01-27-28.seg114.1,ParlaMint-IS_2022-01-27-28.u58,I will not vote with this case.,"[-0.0003005359, 0.038990907, 0.017069632, -0.0..."
9998,ParlaMint-IS_2022-01-27-28.seg114.2,ParlaMint-IS_2022-01-27-28.u58,I won't get in the way of this case.,"[-0.035732668, 0.06427993, 0.012762982, 0.0055..."
9999,ParlaMint-IS_2022-01-27-28.seg114.3,ParlaMint-IS_2022-01-27-28.u58,I will be embarrassed by the release of this c...,"[0.0052291956, -0.08047595, 0.11588394, -0.041..."

#### 3.2 Save output to pickle file

In [23]:
df_parlamint.to_pickle("df_parlamint_all-MiniLM-L6-v2.pkl")

#### 3.3 Encode Dataset with TF-IDF

In [24]:
# Adding the whole parlamint dataset as vocabulary
tfidf_model = TfIdfEmbedder(vocabulary=df_parlamint["Text"].to_list(), max_features=100, stop_words='english')

# Encode sentence-wise dataset
tfidf_embeddings_per_sentence = tfidf_model.embed(df_parlamint["Text"].to_list())

Call 'transform' only...

In [25]:
print(f"Number features: {len(tfidf_model.embedding_model.get_feature_names_out())}", tfidf_model.embedding_model.get_feature_names_out())
print(f"Shape embedding array: {tfidf_embeddings_per_sentence.toarray().shape}")
tfidf_embeddings_per_sentence.toarray()

Number features: 100 ['000' 'able' 'agree' 'ask' 'believe' 'better' 'business' 'care' 'case'
 'change' 'changes' 'children' 'clear' 'come' 'committee' 'community'
 'companies' 'council' 'country' 'course' 'decision' 'discussion' 'does'
 'don' 'economic' 'epidemic' 'especially' 'example' 'fact' 'financial'
 'general' 'going' 'good' 'government' 'health' 'highest' 'hospital'
 'iceland' 'important' 'increase' 'just' 'know' 'land' 'law' 'laws' 'like'
 'long' 'look' 'lot' 'make' 'management' 'matter' 'measures' 'members'
 'mental' 'minister' 'ministers' 'ministry' 'money' 'national' 'need'
 'new' 'number' 'order' 'pay' 'people' 'place' 'point' 'possible'
 'president' 'problem' 'public' 'really' 'report' 'right' 'rights' 'said'
 'say' 'security' 'senator' 'service' 'situation' 'social' 'society'
 'state' 'support' 'taken' 'talk' 'thank' 'things' 'think' 'time' 'today'
 'use' 've' 'want' 'way' 'work' 'year' 'years']
Shape embedding array: (10000, 100)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
df_parlamint["embedding"] = list(tfidf_embeddings_per_sentence.toarray())
df_parlamint

,ID,Parent_ID,Text,embedding
0,ParlaMint-IS_2022-01-17-20.seg2.1,ParlaMint-IS_2022-01-17-20.u1,President of the United States reports:,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,ParlaMint-IS_2022-01-17-20.seg3.1,ParlaMint-IS_2022-01-17-20.u1,"I have decided, according to the proposal of t...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,ParlaMint-IS_2022-01-17-20.seg4.1,ParlaMint-IS_2022-01-17-20.u1,"Arrange sites, January 11th, 2022.","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,ParlaMint-IS_2022-01-17-20.seg6.1,ParlaMint-IS_2022-01-17-20.u1,Katrín Jakobsdóttir's daughter.,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,ParlaMint-IS_2022-01-17-20.seg7.1,ParlaMint-IS_2022-01-17-20.u1,Presidential Letters for a meeting of the Gene...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
...,...,...,...,...
9995,ParlaMint-IS_2022-01-27-28.seg113.4,ParlaMint-IS_2022-01-27-28.u58,"Some of these are good, but the big picture is...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
9996,ParlaMint-IS_2022-01-27-28.seg113.5,ParlaMint-IS_2022-01-27-28.u58,The variable was never taken out whether it wa...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
9997,ParlaMint-IS_2022-01-27-28.seg114.1,ParlaMint-IS_2022-01-27-28.u58,I will not vote with this case.,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, ..."
9998,ParlaMint-IS_2022-01-27-28.seg114.2,ParlaMint-IS_2022-01-27-28.u58,I won't get in the way of this case.,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.719..."
9999,ParlaMint-IS_2022-01-27-28.seg114.3,ParlaMint-IS_2022-01-27-28.u58,I will be embarrassed by the release of this c...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.339..."

#### 3.4 Save output to pickle file

In [27]:
df_parlamint.to_pickle("df_parlamint_all-tfidf.pkl")

#### 3.5 Load data from pickle file

In [28]:
# df_read_parlamint = pd.read_pickle("<filename_path>.pkl")
df_parlamint = pd.read_pickle("df_parlamint_all-MiniLM-L6-v2.pkl")

### 4. Calculate similarities between embeddings

In [29]:
from sentence_transformers import SentenceTransformer, util
from sklearn.metrics.pairwise import cosine_similarity

st_model_small = SentenceTransformer('all-minilm-l6-v2')

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [30]:
# 1. Example data
sentences = [
    "I deposited my paycheck at the bank yesterday.",
    "We had a picnic on the bank of the river.",
    "The financial institution announced a new savings account plan.",
    "She withdrew cash from the nearest ATM.",
    "The kids played near the riverbank after school."
]

query = "financial services"

# 2. Sentence Transformers embeddings
dense_embeddings_sentences = st_model_small.encode(sentences, convert_to_tensor=False)
dense_embeddings_query = st_model_small.encode([query], convert_to_tensor=False)
dense_similarities = util.cos_sim(dense_embeddings_query, dense_embeddings_sentences)[0].cpu().numpy()

# 3. TF-IDF embeddings
tfidf_model = TfIdfEmbedder(vocabulary=sentences, max_features=10, stop_words='english')
tfidf_embeddings_sentences = tfidf_model.embed(sentences)
tfidf_embeddings_query = tfidf_model.embed([query])
tfidf_similarities = cosine_similarity(tfidf_embeddings_query, tfidf_embeddings_sentences).flatten()

# 4. Compare rankings
df = pd.DataFrame({
    "sentence": sentences,
    "tfidf_similarity": tfidf_similarities,
    "st_similarity": dense_similarities
})
# df.sort_values(by=["st_similarity"], ascending=False, inplace=True)
df

Call 'transform' only...
Call 'transform' only...

,sentence,tfidf_similarity,st_similarity
0,I deposited my paycheck at the bank yesterday.,0.0,0.243795
1,We had a picnic on the bank of the river.,0.0,0.047487
2,The financial institution announced a new savi...,0.5,0.322175
3,She withdrew cash from the nearest ATM.,0.0,0.237477
4,The kids played near the riverbank after school.,0.0,0.080024

### 5. How to build a Simple QA System

#### 5.1 Get the Most Likely Utterance

In [31]:
import numpy as np
from sentence_transformers import util

# Given question
question = "What is the government policy on climate change?"
# question = "What about president of america?"

# 1. Embed the question
question_embedding = st_model_small.encode(question)

# 2. Compute cosine similarities
cosine_similarities = util.cos_sim(question_embedding, df_parlamint["embedding"])[0].cpu().numpy()

# 3. Get the index of the most similar utterance
most_similar_idx = int(np.argmax(cosine_similarities))

# 4. Retrieve the most similar text
most_similar_text = df_parlamint.iloc[most_similar_idx]["Text"]
# most_similar_text
print(f"Score: {cosine_similarities[most_similar_idx]:.4f} | Utterance: {most_similar_text}\n")

Score: 0.6772 | Utterance: So we're going to make it even. by the Minister's implementation of the government's strategy for climate change and by the process of climate management in its new formulation, public analysis of measures and other government policies.

In [32]:
len(df_parlamint["embedding"].iloc[1])

384

In [33]:
df_parlamint["Text"]

0                 President of the United States reports:
1       I have decided, according to the proposal of t...
2                      Arrange sites, January 11th, 2022.
3                         Katrín Jakobsdóttir's daughter.
4       Presidential Letters for a meeting of the Gene...
                              ...
9995    Some of these are good, but the big picture is...
9996    The variable was never taken out whether it wa...
9997                      I will not vote with this case.
9998                 I won't get in the way of this case.
9999    I will be embarrassed by the release of this c...
Name: Text, Length: 10000, dtype: object

#### 5.2 Get the Top-K relevant Utterances

In [34]:
question = "What is the government policy on climate change?"
# question = "America?"
k = 5  # choose how many results you want

# 1. Embed the question
question_embedding = st_model_small.encode(question)

# 2. Compute cosine similarities
cosine_similarities = util.cos_sim(question_embedding, df_parlamint["embedding"])[0].cpu().numpy()

# 3. Get indices of top-k most similar utterances
top_k_idx = np.argsort(cosine_similarities)[::-1][:k]

# 4. Retrieve the top-k utterances and their similarity scores
for idx in top_k_idx:
    text = df_parlamint.iloc[idx]["Text"]
    score = cosine_similarities[idx]
    print(f"Score: {score:.4f} | Utterance: {text}\n")

Score: 0.6772 | Utterance: So we're going to make it even. by the Minister's implementation of the government's strategy for climate change and by the process of climate management in its new formulation, public analysis of measures and other government policies.

Score: 0.6287 | Utterance: Is it consistent with the left-green climate policy?

Score: 0.6216 | Utterance: Does Ministers believe that a silicar's restarting can harmonize with the outlook and policy of the nation on climate?

Score: 0.6040 | Utterance: There is an emergency, Mrs. President, on climate issues, and this bill responds to that crisis by suggesting changes that will enable governments to be more effective and that will simply require them to face the climate crisis, the most important solution we are facing.

Score: 0.5818 | Utterance: In the 3rd. The bill suggests that the government's action programme on climate matters will be much more extensive, a better estimate of the estimated costs and the assessment of the environmental benefits of all action, as well as the natural need to reflect the increased ambition proposed to legalize this bill.

In [35]:
tfidf_model = TfIdfEmbedder(vocabulary=df_parlamint["Text"], max_features=1000, stop_words='english')
tfidf_embeddings_sentences = tfidf_model.embed(df_parlamint["Text"].to_list())

Call 'transform' only...

In [36]:
df_parlamint["embedding"] = list(tfidf_embeddings_sentences.toarray())

In [37]:
question = "What is the government policy on climate change?"
# question = "America?"
k = 5  # choose how many results you want

# 1. Embed the question
#question_embedding = tfidf_model.encode(question)
question_embedding = tfidf_model.embed([question])

# 2. Compute cosine similarities
cosine_similarities = util.cos_sim(question_embedding.toarray(), df_parlamint["embedding"])[0].cpu().numpy()

# 3. Get indices of top-k most similar utterances
top_k_idx = np.argsort(cosine_similarities)[::-1][:k]

# 4. Retrieve the top-k utterances and their similarity scores
for idx in top_k_idx:
    text = df_parlamint.iloc[idx]["Text"]
    score = cosine_similarities[idx]
    print(f"Score: {score:.4f} | Utterance: {text}\n")

Call 'transform' only...
Score: 0.6444 | Utterance: Synchronize bill with government policy.

Score: 0.5579 | Utterance: Climate change is here and it's today, just like us.

Score: 0.5479 | Utterance: The government must be stopped after a health-irritation policy.

Score: 0.5448 | Utterance: There is no regional policy in this.

Score: 0.5416 | Utterance: Is it consistent with the left-green climate policy?

In [38]:
import numpy as np
np.where(question_embedding.toarray() > 0)

(array([0, 0, 0, 0]), array([134, 148, 385, 674]))

In [41]:
print(f"Number features: {len(tfidf_model.embedding_model.get_feature_names_out())}", tfidf_model.embedding_model.get_feature_names_out())
print(f"Shape embedding array: {tfidf_embeddings_sentences.toarray().shape}")
df_tfidf_output = pd.DataFrame(columns=tfidf_model.embedding_model.get_feature_names_out(), data=tfidf_embeddings_sentences.toarray())

Number features: 1000 ['000' '10' '12' '15' '17' '18' '19' '1st' '20' '2018' '2020' '2021'
 '2022' '30' '40' '50' '500' 'ability' 'able' 'abroad' 'absolutely'
 'abuse' 'accept' 'accepted' 'access' 'accordance' 'according' 'account'
 'achieve' 'act' 'action' 'actions' 'activation' 'active' 'activities'
 'activity' 'actually' 'add' 'added' 'addiction' 'addition' 'additional'
 'adjustments' 'administration' 'administrative' 'adopted' 'advance'
 'advantage' 'advice' 'advisers' 'affairs' 'affect' 'affected' 'afraid'
 'age' 'agency' 'ago' 'agree' 'agreed' 'agreement' 'agreements' 'ahead'
 'air' 'airport' 'allow' 'allowed' 'analysis' 'answer' 'answers'
 'apartments' 'application' 'applications' 'applies' 'apply' 'approach'
 'appropriate' 'area' 'areas' 'arrangement' 'article' 'ask' 'asked'
 'asking' 'assembly' 'assessment' 'attention' 'authorities' 'authority'
 'available' 'average' 'aware' 'away' 'bad' 'balance' 'bank' 'based'
 'basic' 'basis' 'began' 'beginning' 'believe' 'benefit' 'benefits' 'best'
 'better' 'big' 'billion' 'bit' 'board' 'bring' 'britain' 'brought'
 'bucks' 'budget' 'build' 'building' 'built' 'business' 'businesses'
 'called' 'calling' 'came' 'capital' 'care' 'careful' 'carried' 'carry'
 'case' 'cases' 'cause' 'certain' 'certainly' 'challenge' 'challenges'
 'change' 'changed' 'changes' 'changing' 'child' 'children' 'christmas'
 'circumstances' 'citizens' 'city' 'civil' 'class' 'clear' 'clearly'
 'climate' 'close' 'coastal' 'come' 'comes' 'coming' 'comments'
 'commission' 'committee' 'committees' 'common' 'communication'
 'communities' 'community' 'companies' 'company' 'comparable' 'compared'
 'competitive' 'complete' 'completely' 'concern' 'concerned' 'conclusion'
 'condition' 'conditions' 'conference' 'congress' 'connection'
 'consequences' 'consider' 'considerable' 'consideration' 'considered'
 'considering' 'constitution' 'construction' 'consultation' 'consumers'
 'consumption' 'context' 'continue' 'continued' 'contract' 'contracts'
 'contribute' 'control' 'convention' 'conversation' 'cooperation' 'cope'
 'correct' 'cost' 'costs' 'council' 'countries' 'country' 'course' 'court'
 'covid' 'create' 'crime' 'criminal' 'crisis' 'criteria' 'critical'
 'criticism' 'cross' 'cultural' 'culture' 'current' 'cut' 'damage' 'data'
 'date' 'day' 'days' 'deal' 'dealing' 'debt' 'decades' 'december'
 'decided' 'decision' 'decisions' 'defined' 'degree' 'demand' 'department'
 'departments' 'design' 'despite' 'determine' 'determined' 'developed'
 'development' 'did' 'didn' 'difference' 'different' 'difficult' 'direct'
 'direction' 'directly' 'directors' 'disability' 'disabled' 'disaster'
 'disasters' 'discrimination' 'discuss' 'discussed' 'discussing'
 'discussion' 'discussions' 'disease' 'divorce' 'does' 'doesn' 'doing'
 'dollars' 'domestic' 'don' 'doubt' 'drug' 'drugs' 'earlier' 'easier'
 'economic' 'economy' 'education' 'eea' 'effect' 'effective' 'effects'
 'efficiency' 'efficient' 'effort' 'election' 'electrical' 'electricity'
 'emergency' 'emphasis' 'employees' 'employment' 'encourage' 'end'
 'energy' 'enjoy' 'enormous' 'ensure' 'enter' 'enterprises' 'entire'
 'environment' 'environmental' 'epidemic' 'equal' 'equality' 'especially'
 'establish' 'established' 'europe' 'european' 'evaluate' 'events'
 'evidence' 'exactly' 'examine' 'examined' 'example' 'examples'
 'exception' 'exchange' 'expect' 'expected' 'expenses' 'experience'
 'experts' 'explain' 'explanation' 'extended' 'extent' 'extremely' 'face'
 'fact' 'factor' 'factors' 'failure' 'fall' 'families' 'family' 'far'
 'fear' 'feel' 'felt' 'field' 'fight' 'final' 'finally' 'finance'
 'financial' 'fine' 'finish' 'fish' 'fishing' 'flight' 'focus' 'follow'
 'followed' 'following' 'food' 'force' 'foreign' 'form' 'forward' 'free'
 'freedom' 'fully' 'fund' 'funding' 'funds' 'future' 'general' 'generally'
 'generals' 'getting' 'given' 'glad' 'goal' 'goals' 'goes' 'going' 'gone'
 'gonna' 'good' 'got' 'government' 'governments' 'granted' 'great'
 'greater' 'greatest' 'greatly' 'green' 'ground' 'grounds' 'group'
 'groups' 'grow' 'growing' 'growth' 'half' 'hall' 'hand' 'handle'
 'handled' 'hands' 'happen' 'happened' 'happens' 'happy' 'hard' 'harmony'
 'having' 'head' 'health' 'hear' 'heard' 'held' 'help' 'high' 'higher'
 'highest' 'history' 'home' 'homes' 'hope' 'hopefully' 'hospital' 'hours'
 'house' 'housing' 'huge' 'human' 'hv' 'iceland' 'icelanders' 'icelandic'
 'idea' 'illness' 'immediately' 'impact' 'implementation' 'importance'
 'important' 'improve' 'improved' 'improvement' 'improvements' 'include'
 'includes' 'including' 'income' 'increase' 'increased' 'increasing'
 'independence' 'independent' 'individual' 'individuals' 'industrial'
 'industry' 'infection' 'inflation' 'information' 'informed'
 'infrastructure' 'innovation' 'inquiry' 'instead' 'institute'
 'institution' 'institutions' 'insurance' 'intended' 'interesting'
 'interests' 'international' 'introduced' 'investment' 'invisible'
 'involved' 'isn' 'isolation' 'issue' 'issues' 'january' 'job' 'jobs'
 'just' 'justice' 'key' 'kind' 'kinds' 'know' 'knowledge' 'known' 'labour'
 'lack' 'land' 'landsnet' 'language' 'large' 'largest' 'late' 'later'
 'law' 'laws' 'lead' 'learn' 'led' 'left' 'legal' 'legislation'
 'legislature' 'let' 'level' 'levels' 'life' 'light' 'like' 'likely'
 'limit' 'limitations' 'limited' 'limits' 'line' 'lines' 'list' 'little'
 'live' 'lives' 'living' 'll' 'loan' 'loans' 'local' 'long' 'longer'
 'look' 'looking' 'loss' 'lost' 'lot' 'low' 'lower' 'madam' 'main'
 'maintain' 'major' 'majority' 'make' 'makes' 'making' 'man' 'management'
 'march' 'market' 'marriage' 'material' 'matter' 'matters' 'maybe' 'mean'
 'means' 'measure' 'measures' 'media' 'medical' 'meet' 'meeting'
 'meetings' 'member' 'members' 'men' 'mental' 'mention' 'mentioned' 'met'
 'middle' 'million' 'mind' 'minister' 'ministers' 'ministry' 'money'
 'monitoring' 'month' 'months' 'moving' 'names' 'nation' 'national'
 'nations' 'natural' 'nature' 'nearly' 'necessarily' 'necessary' 'need'
 'needed' 'needs' 'negative' 'new' 'news' 'normal' 'north' 'norway'
 'noted' 'november' 'nuclear' 'number' 'numbers' 'nurses' 'objective'
 'obligation' 'obvious' 'offer' 'office' 'old' 'older' 'ones' 'open'
 'opening' 'operation' 'operators' 'opinion' 'opinions' 'opportunities'
 'opportunity' 'opposition' 'option' 'options' 'order' 'organization'
 'organizational' 'outside' 'overall' 'owners' 'paid' 'pandemic' 'parents'
 'paritaprevir' 'parliament' 'particular' 'particularly' 'parties' 'parts'
 'party' 'passed' 'past' 'patients' 'pay' 'paying' 'payment' 'peace'
 'pension' 'people' 'perform' 'period' 'permission' 'permit' 'person'
 'physical' 'place' 'placed' 'places' 'plan' 'planning' 'plans' 'point'
 'pointed' 'points' 'police' 'policies' 'policy' 'political' 'poor'
 'population' 'position' 'positive' 'possibility' 'possible' 'poverty'
 'power' 'powerful' 'prepared' 'present' 'presented' 'president'
 'pressure' 'prevent' 'prevention' 'previous' 'previously' 'price'
 'prices' 'primarily' 'prime' 'prison' 'private' 'probably' 'problem'
 'problems' 'procedure' 'procedures' 'process' 'produce' 'production'
 'products' 'professional' 'professionals' 'program' 'progress' 'project'
 'projects' 'promote' 'properly' 'property' 'proposal' 'proposed'
 'protect' 'protection' 'provide' 'provided' 'provision' 'public'
 'published' 'punishment' 'purpose' 'putting' 'quality' 'question'
 'questions' 'quite' 'radio' 'range' 'rate' 'reach' 'read' 'ready' 'real'
 'realize' 'really' 'reason' 'reasonable' 'reasons' 'receive' 'received'
 'recent' 'recommend' 'recruitment' 'reduce' 'reduction' 'refer'
 'referred' 'regard' 'regarding' 'regulation' 'regulations' 'related'
 'relationship' 'relationships' 'remember' 'remind' 'rent' 'repeatedly'
 'report' 'reports' 'request' 'require' 'required' 'requirement'
 'requirements' 'requires' 'research' 'resistance' 'resolution'
 'resources' 'respect' 'respectable' 'respond' 'response' 'responsibility'
 'responsible' 'rest' 'restaurant' 'restaurants' 'restrictions' 'result'
 'results' 'return' 'review' 'reviews' 'reykjavík' 'right' 'rights' 'ring'
 'risk' 'road' 'role' 'room' 'rule' 'rules' 'run' 'rural' 'safety' 'said'
 'sale' 'say' 'saying' 'says' 'school' 'schools' 'science' 'scientific'
 'sea' 'second' 'secretary' 'section' 'sector' 'security' 'seek' 'seen'
 'self' 'senate' 'senator' 'senators' 'sense' 'sent' 'service' 'services'
 'set' 'setting' 'seven' 'severe' 'sexual' 'share' 'short' 'shown' 'shows'
 'significant' 'similar' 'simple' 'simply' 'single' 'sit' 'situation'
 'situations' 'small' 'smaller' 'social' 'society' 'solution' 'solutions'
 'solve' 'soon' 'sort' 'source' 'sources' 'southnes' 'space' 'speak'
 'special' 'specific' 'specifically' 'speech' 'spiritual' 'spoke' 'spread'
 'staff' 'stage' 'stand' 'standard' 'start' 'started' 'state' 'stated'
 'states' 'status' 'stay' 'step' 'steps' 'stop' 'story' 'strength'
 'strengthen' 'stress' 'strong' 'structure' 'study' 'subject' 'submitted'
 'success' 'successful' 'suggest' 'suggested' 'suggestion' 'suggestions'
 'suggests' 'summer' 'supply' 'support' 'supposed' 'sure' 'synonym'
 'systems' 'table' 'taken' 'takes' 'taking' 'talk' 'talking' 'task' 'tax'
 'taxes' 'team' 'tell' 'temporary' 'term' 'terms' 'test' 'text' 'thank'
 'thing' 'things' 'think' 'thinking' 'thought' 'time' 'times' 'today'
 'told' 'took' 'total' 'totally' 'tourism' 'trade' 'transport' 'travel'
 'treatment' 'treaty' 'true' 'trust' 'try' 'trying' 'turn' 'uncertainty'
 'understand' 'understanding' 'unemployment' 'union' 'united' 'university'
 'urgent' 'use' 'used' 'using' 'value' 'various' 've' 'view' 'viewpoints'
 'views' 'violence' 'virus' 'vision' 'vital' 'wait' 'waiting' 'walls'
 'want' 'wanted' 'wants' 'way' 'ways' 'weapons' 'week' 'weeks' 'welfare'
 'went' 'west' 'wish' 'women' 'word' 'words' 'work' 'worked' 'workers'
 'working' 'works' 'world' 'worse' 'worst' 'written' 'wrong' 'year'
 'years' 'yes' 'yesterday' 'young']
Shape embedding array: (10000, 1000)